apiVersion: v1
kind: ReplicationController
metadata:
  name: demo72
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: demo72
  template:
    metadata:
      labels:
        app: demo72
    spec:
      serviceAccount: YOUR
      containers:
      - name: demo72
        image: ${docker-registry}/${docker-namespace}/demo72:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080